# Generated by Django 2.2.4 on 2021-01-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_order',
            name='ret_reason',
            field=models.CharField(blank=True, choices=[('UN', 'Not Specified'), ('Q', 'Quality Issue'), ('D', 'Damaged Delivery'), ('S', 'Size Issue'), ('N', "Don't Need It"), ('L', 'Did not Like It')], default='', max_length=2),
        ),
    ]
