# Generated by Django 2.2.4 on 2021-04-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_auto_20210331_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_order',
            name='closure_status',
            field=models.CharField(blank=True, choices=[('0', 'Return Request Cancelled'), ('1', 'Quality Check Failed'), ('2', 'Refund Issued'), ('3', 'Request Closed')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='return_order',
            name='ret_status',
            field=models.CharField(blank=True, choices=[('X', 'Return Request Cancelled'), ('0', 'Return Request Raised'), ('1', 'Return Request Being Processed'), ('2', 'Return Shipment Booked'), ('3', 'Return Shipment Picked Up'), ('4', 'Return Shipment Received by ArteVenue'), ('5', 'Quality Check In Process'), ('6', 'Quality Check Failed'), ('7', 'Quality Check Passed'), ('8', 'Refund Issued'), ('9', 'Request Closed')], default='0', max_length=2),
        ),
    ]
