# Generated by Django 2.2.4 on 2021-05-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_auto_20210416_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_order',
            name='closure_status',
            field=models.CharField(blank=True, choices=[('0', 'Return Request Cancelled'), ('1', 'Quality Check Failed'), ('2', 'Refund Issued')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='return_order',
            name='ret_status',
            field=models.CharField(blank=True, choices=[('X', 'Request Cancelled'), ('0', 'Request Raised'), ('1', 'Request Being Processed'), ('2', 'Shipment Booked'), ('3', 'Shipment Picked Up'), ('4', 'Shipment Received by ArteVenue'), ('5', 'Quality Check In Process'), ('6', 'Quality Check Failed'), ('7', 'Quality Check Passed'), ('8', 'Refund Issued'), ('9', 'Request Closed')], default='0', max_length=2),
        ),
    ]
