# Generated by Django 2.2.4 on 2020-02-13 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_author',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('website_url', models.SlugField(blank=True, max_length=500, null=True)),
                ('facebook_url', models.SlugField(blank=True, max_length=500, null=True)),
                ('instagram_url', models.SlugField(blank=True, max_length=500, null=True)),
                ('twitter_url', models.SlugField(blank=True, max_length=500, null=True)),
                ('profile', models.CharField(max_length=2000)),
                ('profile_pic', models.ImageField(blank=True, default='', upload_to='egift_cards/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=600)),
                ('post', tinymce.models.HTMLField()),
                ('is_published', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(default=False)),
                ('expiry_date', models.DateTimeField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog_author')),
            ],
        ),
        migrations.CreateModel(
            name='Blog_post_comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=2000)),
                ('is_published', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog_post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_post_comment_reply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply', models.CharField(max_length=2000)),
                ('is_published', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog_post')),
                ('blog_post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog_post_comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
