# Generated by Django 2.2.4 on 2020-02-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='expiry_date',
        ),
    ]
