# Generated by Django 2.2.4 on 2020-02-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_post_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='background_image_url',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
