# Generated by Django 2.1.4 on 2019-03-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0003_auto_20190306_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_view',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available_on', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('part_number', models.CharField(max_length=30, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('seo_description', models.CharField(max_length=300, null=True)),
                ('seo_title', models.CharField(max_length=70, null=True)),
                ('charge_taxes', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('has_variants', models.BooleanField(default=False)),
                ('aspect_ratio', models.DecimalField(decimal_places=18, max_digits=21, null=True)),
                ('image_type', models.CharField(max_length=1, null=True)),
                ('orientation', models.CharField(max_length=20, null=True)),
                ('max_width', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('max_height', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('min_width', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('publisher', models.CharField(max_length=600, null=True)),
                ('artist', models.CharField(max_length=600, null=True)),
                ('colors', models.CharField(max_length=600, null=True)),
                ('key_words', models.CharField(max_length=2000, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=1000)),
                ('thumbnail_url', models.CharField(blank=True, default='', max_length=1000)),
                ('session_id', models.CharField(blank=True, default='', max_length=40)),
                ('image_to_frame', models.ImageField(blank=True, default='', upload_to='uploads/%Y/%m/%d/')),
                ('status', models.CharField(blank=True, max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('collage_layout_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'product_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion_product_view',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
            ],
            options={
                'db_table': 'promotion_product_view',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_type',
        ),
    ]
