# Generated by Django 2.1.4 on 2019-03-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0004_auto_20190315_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_original_art',
            name='cart_item_ptr',
        ),
        migrations.RemoveField(
            model_name='order_original_art',
            name='original_art',
        ),
        migrations.RemoveField(
            model_name='order_stock_collage',
            name='cart_item_ptr',
        ),
        migrations.RemoveField(
            model_name='order_stock_collage',
            name='stock_collage',
        ),
        migrations.RemoveField(
            model_name='order_stock_image',
            name='cart_item_ptr',
        ),
        migrations.RemoveField(
            model_name='order_stock_image',
            name='stock_image',
        ),
        migrations.RemoveField(
            model_name='order_user_image',
            name='cart_item_ptr',
        ),
        migrations.RemoveField(
            model_name='order_user_image',
            name='user_image',
        ),
        migrations.DeleteModel(
            name='Order_original_art',
        ),
        migrations.DeleteModel(
            name='Order_stock_collage',
        ),
        migrations.DeleteModel(
            name='Order_stock_image',
        ),
        migrations.DeleteModel(
            name='Order_user_image',
        ),
    ]
