# Generated by Django 2.1.4 on 2019-03-22 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0007_order_items_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='store',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='voucher',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist_item',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='wishlist_item',
            name='acrylic',
        ),
        migrations.RemoveField(
            model_name='wishlist_item',
            name='board',
        ),
        migrations.RemoveField(
            model_name='wishlist_item',
            name='moulding',
        ),
        migrations.RemoveField(
            model_name='wishlist_item',
            name='mount',
        ),
        migrations.RemoveField(
            model_name='wishlist_item',
            name='print_medium',
        ),
        migrations.RemoveField(
            model_name='wishlist_item',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='wishlist_item',
            name='stretch',
        ),
        migrations.RemoveField(
            model_name='wishlist_item',
            name='wishlist',
        ),
        migrations.RemoveField(
            model_name='wishlist_original_art',
            name='cart_item_ptr',
        ),
        migrations.RemoveField(
            model_name='wishlist_original_art',
            name='original_art',
        ),
        migrations.RemoveField(
            model_name='wishlist_stock_collage',
            name='cart_item_ptr',
        ),
        migrations.RemoveField(
            model_name='wishlist_stock_collage',
            name='stock_collage',
        ),
        migrations.RemoveField(
            model_name='wishlist_stock_image',
            name='cart_item_ptr',
        ),
        migrations.RemoveField(
            model_name='wishlist_stock_image',
            name='stock_image',
        ),
        migrations.RemoveField(
            model_name='wishlist_user_image',
            name='cart_item_ptr',
        ),
        migrations.RemoveField(
            model_name='wishlist_user_image',
            name='user_image',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='Wishlist_item',
        ),
        migrations.DeleteModel(
            name='Wishlist_original_art',
        ),
        migrations.DeleteModel(
            name='Wishlist_stock_collage',
        ),
        migrations.DeleteModel(
            name='Wishlist_stock_image',
        ),
        migrations.DeleteModel(
            name='Wishlist_user_image',
        ),
    ]
