# Generated by Django 2.1.4 on 2019-04-20 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artevenue', '0010_publisher_error_stock_image_category_error_stock_image_error_stock_image_stock_image_category_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Please enter your friend's Name", max_length=150)),
                ('email_id', models.EmailField(help_text='Mandatory: Please enter correct email Id', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Optional: Will help us to reach your friend in case of any issues in rewards', max_length=30, null=True)),
                ('message', models.CharField(help_text='Your message will be included in the email we send', max_length=2000)),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
