# Generated by Django 2.1.4 on 2019-05-01 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0011_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='referral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Referral'),
        ),
        migrations.AddField(
            model_name='order',
            name='referral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Referral'),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_disc_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='referral',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='referee_claimed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_by_claimed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='email_id',
            field=models.EmailField(error_messages={'blank': 'Email id is required', 'unique': 'This email id is already used in a referral'}, help_text='Mandatory: Please enter correct email Id', max_length=254, unique=True),
        ),
    ]
