# Generated by Django 2.1.4 on 2019-05-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0012_auto_20190501_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='referral_disc_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
