# Generated by Django 2.1.4 on 2019-05-02 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0013_cart_referral_disc_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curated_category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artevenue.Ecom_site')),
            ],
        ),
        migrations.CreateModel(
            name='Curated_collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curated_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artevenue.Curated_category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artevenue.Stock_image')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artevenue.Product_type')),
            ],
        ),
    ]
