# Generated by Django 2.1.4 on 2019-05-03 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artevenue', '0014_curated_category_curated_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egift',
            fields=[
                ('gift_rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('gift_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=2000)),
                ('receiver_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payment_status', models.CharField(blank=True, default='IN', max_length=2)),
                ('gift_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Egift_card_design',
            fields=[
                ('design_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('url', models.CharField(max_length=256, null=True)),
                ('amount_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Egift_redemption',
            fields=[
                ('redemption_id', models.AutoField(primary_key=True, serialize=False)),
                ('redemption_date', models.DateField(blank=True, null=True)),
                ('redemption_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('egift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artevenue.Egift')),
            ],
        ),
        migrations.AddField(
            model_name='egift',
            name='egift_card_design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.Egift_card_design'),
        ),
        migrations.AddField(
            model_name='egift',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egift_giver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='egift',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='egift_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='egift',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.Voucher'),
        ),
    ]
