# Generated by Django 2.1.4 on 2019-05-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0015_auto_20190503_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egift',
            name='gift_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
