# Generated by Django 2.1.4 on 2019-05-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0016_auto_20190503_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='egift',
            name='receiver_name',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='egift',
            name='receiver_phone',
            field=models.CharField(blank=True, help_text='Optional: Will help us to reach the receiver in case of any issues', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='egift',
            name='receiver_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
