# Generated by Django 2.1.4 on 2019-05-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0018_egift_card_design_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egift_card_design',
            name='location',
        ),
        migrations.AddField(
            model_name='egift_card_design',
            name='text_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='egift_card_design',
            name='text_location',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
