# Generated by Django 2.1.4 on 2019-05-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0019_auto_20190505_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_details',
            fields=[
                ('first_name', models.CharField(blank=True, default='', max_length=500)),
                ('last_name', models.CharField(blank=True, default='', max_length=500)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('email_id', models.EmailField(blank=True, default='', max_length=254)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_txn_status', models.CharField(blank=True, default='', max_length=10)),
                ('payment_txn_id', models.CharField(blank=True, default='', max_length=250)),
                ('payment_txn_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('payment_txn_posted_hash', models.CharField(blank=True, default='', max_length=250)),
                ('payment_txn_key', models.CharField(blank=True, default='', max_length=250)),
                ('payment_txn_productinfo', models.CharField(blank=True, default='', max_length=250)),
                ('payment_txn_email', models.CharField(blank=True, default='', max_length=250)),
                ('payment_txn_salt', models.CharField(blank=True, default='', max_length=250)),
                ('payment_firstname', models.CharField(blank=True, default='', max_length=250)),
                ('payment_lastname', models.CharField(blank=True, default='', max_length=250)),
                ('payment_email', models.CharField(blank=True, default='', max_length=250)),
                ('payment_phone', models.CharField(blank=True, default='', max_length=20)),
                ('payment_address1', models.CharField(blank=True, default='', max_length=250)),
                ('payment_address2', models.CharField(blank=True, default='', max_length=250)),
                ('payment_city', models.CharField(blank=True, default='', max_length=250)),
                ('payment_state', models.CharField(blank=True, default='', max_length=250)),
                ('payment_country', models.CharField(blank=True, default='', max_length=250)),
                ('payment_zip_code', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PrePaymentGateway',
            fields=[
                ('first_name', models.CharField(blank=True, default='', max_length=500)),
                ('last_name', models.CharField(blank=True, default='', max_length=500)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('email_id', models.EmailField(blank=True, default='', max_length=254)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
