# Generated by Django 2.1.4 on 2019-05-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0020_payment_details_prepaymentgateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_details',
            name='cust_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment_details',
            name='factory_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('PP', 'Payment Pending'), ('PR', 'In Process'), ('SH', 'Ready for Shipping'), ('IN', 'In Transit'), ('CO', 'Delivered')], default='PP', max_length=2),
        ),
    ]
