# Generated by Django 2.1.4 on 2019-05-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0022_auto_20190527_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_details',
            old_name='order_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='prepaymentgateway',
            old_name='order_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='payment_details',
            name='rec_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_details',
            name='trn_type',
            field=models.CharField(blank=True, choices=[('ORD', 'Order'), ('EGF', 'Egift')], default='ORD', max_length=3),
        ),
        migrations.AddField(
            model_name='prepaymentgateway',
            name='rec_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prepaymentgateway',
            name='trn_type',
            field=models.CharField(blank=True, choices=[('ORD', 'Order'), ('EGF', 'Egift')], default='ORD', max_length=3),
        ),
        migrations.AlterField(
            model_name='egift',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PP', 'Payment Pending'), ('PC', 'Payment Complete'), ('PR', 'pending redemption'), ('PC', 'Partial Redemption'), ('RC', 'Redemption Complete')], default='PP', max_length=2),
        ),
    ]
