# Generated by Django 2.1.4 on 2019-05-28 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0023_auto_20190528_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voucher_user',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher_user',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='egift',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PP', 'Payment Pending'), ('PC', 'eGift Pending to be Redeemed'), ('PM', 'Partial Redemption Done'), ('RC', 'eGift Order Comleted - Redemption done'), ('EX', 'eGift Order Expired')], default='PP', max_length=2),
        ),
    ]
