# Generated by Django 2.1.4 on 2019-05-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0024_auto_20190528_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='egift',
            name='giver_email_sent',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='egift',
            name='receiver_email_sent',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
