# Generated by Django 2.1.4 on 2019-05-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0025_auto_20190530_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='egift_card_design',
            name='voucher_location',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
