# Generated by Django 2.1.4 on 2019-05-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0026_egift_card_design_voucher_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='egift',
            name='card_image',
            field=models.ImageField(blank=True, default='', upload_to='egift_cards/%Y/%m/%d/'),
        ),
    ]
