# Generated by Django 2.1.4 on 2019-06-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0027_egift_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generate_number',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('current_number', models.IntegerField()),
            ],
        ),
    ]
