# Generated by Django 2.1.4 on 2019-06-15 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0028_generate_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='eGift_sms_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email_sent', models.BooleanField(default=False)),
                ('factory_email_sent', models.BooleanField(default=False)),
                ('customer_sms_sent', models.BooleanField(default=False)),
                ('factory_sms_sent', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('egift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artevenue.Egift')),
            ],
        ),
        migrations.CreateModel(
            name='Order_sms_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email_sent', models.BooleanField(default=False)),
                ('factory_email_sent', models.BooleanField(default=False)),
                ('customer_sms_sent', models.BooleanField(default=False)),
                ('factory_sms_sent', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artevenue.Order')),
            ],
        ),
    ]
