# Generated by Django 2.1.4 on 2019-06-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0029_egift_sms_email_order_sms_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_billing',
            name='gst_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='gst_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='tax_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
