# Generated by Django 2.1.4 on 2019-06-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0030_auto_20190628_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_billing_address',
            name='gst_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
