# Generated by Django 2.1.4 on 2019-07-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0031_user_billing_address_gst_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egift_sms_email',
            old_name='customer_email_sent',
            new_name='giver_email_sent',
        ),
        migrations.RenameField(
            model_name='egift_sms_email',
            old_name='customer_sms_sent',
            new_name='giver_sms_sent',
        ),
        migrations.RenameField(
            model_name='egift_sms_email',
            old_name='factory_email_sent',
            new_name='receiver_email_sent',
        ),
        migrations.RenameField(
            model_name='egift_sms_email',
            old_name='factory_sms_sent',
            new_name='receiver_sms_sent',
        ),
        migrations.AlterField(
            model_name='egift',
            name='giver_email_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='egift',
            name='receiver_email_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
