# Generated by Django 2.1.4 on 2019-07-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0032_auto_20190716_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_image',
            name='image_to_frame_thumbnail',
            field=models.ImageField(blank=True, default='', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
