# Generated by Django 2.1.4 on 2019-07-23 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artevenue', '0033_user_image_image_to_frame_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.PositiveSmallIntegerField(choices=[(1, 'Business Support'), (2, 'Production'), (3, 'Sales'), (4, 'Marketting'), (5, 'Accounts'), (6, 'IT')], null=True)),
                ('is_manager', models.BooleanField(default=False, verbose_name='manager status')),
                ('is_chief', models.BooleanField(default=False, verbose_name='ceo status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
