# Generated by Django 2.1.4 on 2019-07-29 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artevenue', '0034_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_sms_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_email_sent', models.BooleanField(default=False)),
                ('welcome_sms_sent', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_chief',
            field=models.BooleanField(default=False, verbose_name='chief status'),
        ),
    ]
