# Generated by Django 2.1.4 on 2019-07-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0035_auto_20190729_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_profile',
            name='bank_acc_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='business_profile',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AddField(
            model_name='business_profile',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='business_profile',
            name='ifsc_code',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
