# Generated by Django 2.2.4 on 2019-08-08 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0037_image_url_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(blank=True, choices=[('A', 'Store-wide Promotion, applies to all products'), ('C', 'Applies to a particular category'), ('P', 'Applies to select products only')], default='', max_length=1),
        ),
        migrations.CreateModel(
            name='Business_commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(help_text='Commission month (YYYY-MM)', max_length=7)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_in_current_year', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_paid_date', models.DateTimeField(null=True)),
                ('commission_paid_reference', models.CharField(blank=True, default='', max_length=600)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artevenue.Business_profile')),
            ],
        ),
    ]
