# Generated by Django 2.2.4 on 2019-08-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0040_homelane_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homelane_data',
            old_name='category_id',
            new_name='category',
        ),
    ]
