# Generated by Django 2.2.4 on 2019-08-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0041_auto_20190811_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelane_data',
            name='acrylic',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homelane_data',
            name='board',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homelane_data',
            name='category',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homelane_data',
            name='moulding',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homelane_data',
            name='mount',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homelane_data',
            name='promotion',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homelane_data',
            name='stretch',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
