# Generated by Django 2.2.4 on 2019-08-12 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0043_auto_20190812_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelane_data',
            name='acrylic_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='homelane_data',
            name='board_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='homelane_data',
            name='category_name',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='homelane_data',
            name='moulding_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='homelane_data',
            name='mount_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='homelane_data',
            name='print_medium_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='homelane_data',
            name='promotion_name',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='homelane_data',
            name='stretch_name',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='homelane_data',
            name='acrylic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Acrylic'),
        ),
        migrations.AlterField(
            model_name='homelane_data',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Board'),
        ),
        migrations.AlterField(
            model_name='homelane_data',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.Stock_image_category'),
        ),
        migrations.AlterField(
            model_name='homelane_data',
            name='moulding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Moulding'),
        ),
        migrations.AlterField(
            model_name='homelane_data',
            name='mount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Mount'),
        ),
        migrations.AlterField(
            model_name='homelane_data',
            name='print_medium',
            field=models.ForeignKey(default='PAPER', on_delete=django.db.models.deletion.PROTECT, to='artevenue.Print_medium'),
        ),
        migrations.AlterField(
            model_name='homelane_data',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Promotion'),
        ),
        migrations.AlterField(
            model_name='homelane_data',
            name='stretch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Stretch'),
        ),
    ]
