# Generated by Django 2.2.4 on 2019-08-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0045_moulding_width_inner_inches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homelane_data',
        ),
    ]
