# Generated by Django 2.2.4 on 2019-08-29 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artevenue', '0048_amazon_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_collection',
            fields=[
                ('user_collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='original_art',
            name='art_height',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='original_art',
            name='art_medium',
            field=models.CharField(blank=True, choices=[('OIL', 'Oil'), ('ACR', 'Acrylic'), ('WTR', 'Water Color'), ('GOU', 'Gouache'), ('INK', 'Ink'), ('PEN', 'Pen'), ('PST', 'Pastel'), ('PNC', 'Pencil'), ('COL', 'Charcoal')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='original_art',
            name='art_surface',
            field=models.CharField(blank=True, choices=[('CVS', 'CANVAS'), ('PPR', 'PAPER'), ('FAB', 'FABRIC'), ('GLS', 'GLASS'), ('WOD', 'WOOD')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='original_art',
            name='art_surface_desc',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='original_art',
            name='art_width',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='original_art',
            name='high_resolution_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product_type',
            name='apply_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='User_space',
            fields=[
                ('user_space_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artevenue.User_collection')),
            ],
        ),
        migrations.AddField(
            model_name='wishlist_original_art',
            name='user_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.User_collection'),
        ),
        migrations.AddField(
            model_name='wishlist_original_art',
            name='user_space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.User_space'),
        ),
        migrations.AddField(
            model_name='wishlist_stock_collage',
            name='user_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.User_collection'),
        ),
        migrations.AddField(
            model_name='wishlist_stock_collage',
            name='user_space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.User_space'),
        ),
        migrations.AddField(
            model_name='wishlist_stock_image',
            name='user_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.User_collection'),
        ),
        migrations.AddField(
            model_name='wishlist_stock_image',
            name='user_space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.User_space'),
        ),
        migrations.AddField(
            model_name='wishlist_user_image',
            name='user_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.User_collection'),
        ),
        migrations.AddField(
            model_name='wishlist_user_image',
            name='user_space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.User_space'),
        ),
    ]
