# Generated by Django 2.2.4 on 2019-09-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0050_auto_20190906_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecom_site',
            name='email_support_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ecom_site',
            name='gst_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ecom_site',
            name='pan_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ecom_site',
            name='support_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ecom_site',
            name='tan_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
