# Generated by Django 2.2.4 on 2019-09-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0052_invoice_invoice_items_view_invoice_original_art_invoice_stock_collage_invoice_stock_image_invoice_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
