# Generated by Django 2.2.4 on 2019-10-04 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0053_cart_cart_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion_voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_popup', models.BooleanField(default=False)),
                ('pop_at_start', models.BooleanField(default=False)),
                ('pop_at_close', models.BooleanField(default=False)),
                ('popup_duration', models.TimeField(null=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artevenue.Promotion')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artevenue.Voucher')),
            ],
        ),
    ]
