# Generated by Django 2.2.4 on 2019-10-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0054_promotion_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
