# Generated by Django 2.2.4 on 2019-10-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0057_order_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_data',
            name='amazon_sku',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='amazon_data',
            name='parent_child',
            field=models.CharField(choices=[('P', 'Parent'), ('C', 'Child')], default='P', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='amazon_data',
            name='parent_key',
            field=models.IntegerField(null=True),
        ),
    ]
