# Generated by Django 2.2.4 on 2019-10-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0058_auto_20191021_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazon_data',
            name='parent_key',
        ),
    ]
