# Generated by Django 2.2.4 on 2019-10-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0060_amazon_data_parent_amz_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_data',
            name='item_disc_amt',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='amazon_data',
            name='item_sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='amazon_data',
            name='item_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='amazon_data',
            name='item_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='amazon_data',
            name='item_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
