# Generated by Django 2.2.4 on 2019-11-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0061_auto_20191031_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_data',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_status',
            field=models.CharField(blank=True, choices=[('AC', 'Active'), ('AB', 'Abandoned'), ('CO', 'Checked Out')], default='AC', max_length=2),
        ),
        migrations.CreateModel(
            name='Original_art_original_art_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_art', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='artevenue.Original_art')),
                ('original_art_image_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.Stock_image_category')),
            ],
        ),
    ]
