# Generated by Django 2.2.4 on 2019-11-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0063_newsletter_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='original_art_original_art_category',
            old_name='original_art_image_category',
            new_name='stock_image_category',
        ),
    ]
