# Generated by Django 2.2.4 on 2019-11-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0065_auto_20191108_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='email_sent_to_artevenue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact_us',
            name='email_sent_to_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact_us',
            name='sms_sent_to_artevenue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact_us',
            name='sms_sent_to_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='original_art',
            name='art_surface_desc',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
