# Generated by Django 2.2.4 on 2019-11-20 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artevenue', '0067_cart_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_ip_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=40)),
                ('userlogged_in', models.BooleanField(default=False)),
                ('site_visit_datetime', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
