# Generated by Django 2.2.4 on 2019-11-21 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0068_user_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_ip_address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
