# Generated by Django 2.2.4 on 2019-11-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0069_auto_20191121_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_ip_address',
            name='latest_site_visit_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user_ip_address',
            name='num_of_visits',
            field=models.IntegerField(default=1),
        ),
    ]
