# Generated by Django 2.2.4 on 2019-11-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0070_auto_20191121_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='original_art',
            name='art_print_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='original_art',
            name='available_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='original_art',
            name='original_art_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='original_art',
            name='sold_qty',
            field=models.IntegerField(null=True),
        ),
    ]
