# Generated by Django 2.2.4 on 2019-11-26 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0071_auto_20191126_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_art',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.Artist'),
        ),
    ]
