# Generated by Django 2.2.4 on 2019-11-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0075_auto_20191128_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_art',
            name='art_surface',
            field=models.CharField(blank=True, choices=[('CVS', 'Canvas'), ('PPR', 'Paper'), ('FAB', 'Fabric'), ('GLS', 'Glass'), ('WOD', 'Wood')], default='', max_length=3),
        ),
    ]
