# Generated by Django 2.2.4 on 2019-12-05 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0076_auto_20191130_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='original_art',
            name='stock_image_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Stock_image'),
        ),
        migrations.AlterField(
            model_name='original_art',
            name='available_qty',
            field=models.IntegerField(null=True),
        ),
    ]
