# Generated by Django 2.2.4 on 2019-12-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0077_auto_20191205_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='original_art',
            old_name='stock_image_id',
            new_name='stock_image',
        ),
    ]
