# Generated by Django 2.2.4 on 2019-12-11 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0078_auto_20191205_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel_order_amz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artevenue_order_date', models.DateField(blank=True, null=True)),
                ('amazon_order_no', models.CharField(blank=True, default='', max_length=25)),
                ('amazon_order_date', models.DateField(blank=True, null=True)),
                ('buyer_full_name', models.CharField(max_length=500)),
                ('shipping_full_name', models.CharField(max_length=500)),
                ('shipping_address_1', models.CharField(max_length=600)),
                ('shipping_address_2', models.CharField(blank=True, default='', max_length=600)),
                ('shipping_land_mark', models.CharField(blank=True, default='', max_length=600)),
                ('shipping_city', models.CharField(max_length=600)),
                ('shipping_phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('shipping_email_id', models.EmailField(blank=True, default='', max_length=254)),
                ('billing_full_name', models.CharField(max_length=500)),
                ('billing_address_1', models.CharField(max_length=600)),
                ('billing_address_2', models.CharField(blank=True, default='', max_length=600)),
                ('billing_land_mark', models.CharField(blank=True, default='', max_length=600)),
                ('billing_city', models.CharField(max_length=600)),
                ('billing_phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('billing_email_id', models.EmailField(blank=True, default='', max_length=254)),
                ('shipping_mode', models.CharField(blank=True, choices=[('S', 'Self(ArteVenue)'), ('A', 'Amazon')], default='S', max_length=1)),
                ('gst_number', models.CharField(blank=True, default='', max_length=30)),
                ('quantity', models.IntegerField(null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('disc_amt', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('shipped_date', models.DateField(null=True)),
                ('delivered_date', models.DateField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_channel',
            fields=[
                ('channel_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Cart'),
        ),
        migrations.AlterField(
            model_name='order_original_art',
            name='cart_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Cart_item'),
        ),
        migrations.AlterField(
            model_name='order_stock_collage',
            name='cart_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Cart_item'),
        ),
        migrations.AlterField(
            model_name='order_stock_image',
            name='cart_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Cart_item'),
        ),
        migrations.AlterField(
            model_name='order_user_image',
            name='cart_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Cart_item'),
        ),
        migrations.CreateModel(
            name='Channel_order_amz_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_ASIN', models.CharField(max_length=20)),
                ('amazon_order_item_ID', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('disc_amt', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('amazon_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artevenue.Amazon_data')),
                ('channel_order_amz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artevenue.Channel_order_amz')),
            ],
        ),
        migrations.AddField(
            model_name='channel_order_amz',
            name='arteveue_order_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artevenue.Order'),
        ),
        migrations.AddField(
            model_name='channel_order_amz',
            name='billing_country',
            field=models.ForeignKey(default='IND', on_delete=django.db.models.deletion.PROTECT, related_name='billing_country', to='artevenue.Country'),
        ),
        migrations.AddField(
            model_name='channel_order_amz',
            name='billing_pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_pin_code', to='artevenue.Pin_code'),
        ),
        migrations.AddField(
            model_name='channel_order_amz',
            name='billing_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_state', to='artevenue.State'),
        ),
        migrations.AddField(
            model_name='channel_order_amz',
            name='order_channel',
            field=models.ForeignKey(default='AMZ', on_delete=django.db.models.deletion.PROTECT, to='artevenue.Order_channel'),
        ),
        migrations.AddField(
            model_name='channel_order_amz',
            name='shipping_country',
            field=models.ForeignKey(default='IND', on_delete=django.db.models.deletion.PROTECT, related_name='shipping_country', to='artevenue.Country'),
        ),
        migrations.AddField(
            model_name='channel_order_amz',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Shipping_method'),
        ),
        migrations.AddField(
            model_name='channel_order_amz',
            name='shipping_pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_pin_code', to='artevenue.Pin_code'),
        ),
        migrations.AddField(
            model_name='channel_order_amz',
            name='shipping_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_state', to='artevenue.State'),
        ),
    ]
