# Generated by Django 2.2.4 on 2019-12-11 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0079_auto_20191211_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.ForeignKey(default='ART', on_delete=django.db.models.deletion.PROTECT, to='artevenue.Order_channel'),
        ),
    ]
