# Generated by Django 2.2.4 on 2020-01-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0082_auto_20200114_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='business_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='business_profile',
            unique_together=set(),
        ),
    ]
