# Generated by Django 2.2.4 on 2020-01-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0083_auto_20200115_1833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
