# Generated by Django 2.2.4 on 2020-01-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0085_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subject_interests',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
