# Generated by Django 2.2.4 on 2020-01-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0086_userprofile_subject_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_profile',
            name='business_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Not Specified'), ('M', 'Male'), ('F', 'Female'), ('T', 'LGBT')], default='', max_length=1),
        ),
    ]
