# Generated by Django 2.2.4 on 2020-01-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0087_auto_20200116_0749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business_commission',
        ),
    ]
