# Generated by Django 2.2.4 on 2020-01-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0089_business_referral_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deferred_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile_group',
            name='deferred_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile_group',
            name='payment_due_period_days',
            field=models.IntegerField(null=True),
        ),
    ]
