# Generated by Django 2.2.4 on 2020-02-13 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0090_auto_20200128_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_deferred_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mode_of_payment', models.CharField(choices=[('CS', 'Cash'), ('ON', 'Online'), ('CH', 'Cheque'), ('DD', 'Demand Draft'), ('BK', 'BANK TRANSFER - NEFT/IMPS/RTGS')], max_length=2)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artevenue.Order')),
            ],
        ),
    ]
