# Generated by Django 2.2.4 on 2020-02-23 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artevenue', '0091_order_deferred_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel_partner_profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=30)),
                ('partner_discount_type', models.CharField(blank=True, max_length=30)),
                ('partner_discount_percentage', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('client_discount_type', models.CharField(blank=True, max_length=30)),
                ('client_discount_percentage', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('deferred_payment', models.BooleanField(default=True)),
                ('payment_due_period_days', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel_partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=500)),
                ('company', models.CharField(blank=True, max_length=30)),
                ('address_1', models.CharField(max_length=600)),
                ('address_2', models.CharField(blank=True, default='', max_length=600)),
                ('city', models.CharField(max_length=600)),
                ('phone_number', models.CharField(max_length=30)),
                ('gst_number', models.CharField(blank=True, default='', max_length=30)),
                ('tax_id', models.CharField(blank=True, default='', max_length=30)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('bank_acc_no', models.CharField(blank=True, default='', max_length=20)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=11)),
                ('bank_name', models.CharField(blank=True, default='', max_length=500)),
                ('bank_branch', models.CharField(blank=True, default='', max_length=600)),
                ('partner_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('country', models.ForeignKey(default='IND', on_delete=django.db.models.deletion.PROTECT, to='artevenue.Country')),
                ('pin_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Pin_code')),
                ('profile_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.Profile_group')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artevenue.State')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_partner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='business_profile',
            name='channel_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.Channel_partner'),
        ),
    ]
