# Generated by Django 2.2.4 on 2020-03-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0092_auto_20200223_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_data',
            name='card1_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='amazon_data',
            name='card2_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='amazon_data',
            name='card3_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='amazon_data',
            name='card4_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='amazon_data',
            name='card5_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='amazon_data',
            name='card6_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
