# Generated by Django 2.2.4 on 2020-03-24 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0093_auto_20200323_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_collage',
            name='collage_layout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.Collage_layout'),
        ),
        migrations.CreateModel(
            name='Collage_product_stock_image',
            fields=[
                ('collage_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artevenue.Stock_image')),
            ],
        ),
    ]
