# Generated by Django 2.2.4 on 2020-03-25 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0095_auto_20200324_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage_stock_image',
            name='stock_collage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Stock_collage'),
            preserve_default=False,
        ),
    ]
