# Generated by Django 2.2.4 on 2020-03-26 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0096_collage_stock_image_stock_collage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collage_stock_image',
            name='stock_image_category',
        ),
        migrations.AddField(
            model_name='stock_collage',
            name='stock_image_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.Stock_image_category'),
        ),
    ]
