# Generated by Django 2.2.4 on 2020-03-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0097_auto_20200326_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_collage',
            name='aspect_ratio',
            field=models.DecimalField(decimal_places=18, max_digits=21, null=True),
        ),
        migrations.AddField(
            model_name='stock_collage',
            name='colors',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='stock_collage',
            name='key_words',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='stock_collage',
            name='max_height',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock_collage',
            name='max_width',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock_collage',
            name='min_width',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock_collage',
            name='orientation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
