# Generated by Django 2.2.4 on 2020-03-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0098_auto_20200326_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_collage',
            name='thumbnail_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='stock_collage',
            name='url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
