# Generated by Django 2.2.4 on 2020-03-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0099_auto_20200329_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='thumbnail_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
