# Generated by Django 2.2.4 on 2020-03-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0100_auto_20200330_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_collage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
