# Generated by Django 2.2.4 on 2020-04-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0101_stock_collage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='shipper_shipping_method',
            name='slab',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipper_shipping_method',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='shipper_shipping_method',
            name='rate_type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='shipping_method',
            name='name',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('ECONOMY', 'Economy'), ('EXPRESS', 'Express'), ('EXPEDITED', 'Expedited')], max_length=128),
        ),
        migrations.AlterField(
            model_name='shipping_status',
            name='shipping_status_code',
            field=models.CharField(choices=[('IN TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], max_length=128),
        ),
    ]
