# Generated by Django 2.2.4 on 2020-04-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0102_auto_20200415_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
