# Generated by Django 2.2.4 on 2020-05-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0103_order_tracking_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_image_category',
            name='url_suffix',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='product_type_id',
            field=models.CharField(choices=[('STOCK-IMAGE', 'Stock Image'), ('USER-IMAGE', 'Custom Frame'), ('STOCK-COLLAGE', 'Stock Collage Layout'), ('ORIGINAL-ART', 'Original Art'), ('FRAME', 'Frame'), ('TABLE-TOP', 'Tabletop Frame'), ('COLLAGE-FRAME', 'Callage Frame'), ('ART-FRAME', 'Art Frame')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
