# Generated by Django 2.2.4 on 2020-05-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0104_auto_20200522_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='curated_category',
            name='url_suffix',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
