# Generated by Django 2.2.4 on 2020-06-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0105_curated_category_url_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_image_category',
            name='banner_image_codes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
