# Generated by Django 2.2.4 on 2020-06-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0106_stock_image_category_banner_image_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='curated_category',
            name='banner_image_codes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
