# Generated by Django 2.2.4 on 2020-06-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0107_curated_category_banner_image_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='curated_category',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='stock_image_category',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
