# Generated by Django 2.2.4 on 2020-06-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0108_auto_20200606_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='curated_category',
            name='page_description',
            field=models.CharField(blank=True, default='', max_length=165),
        ),
        migrations.AddField(
            model_name='curated_category',
            name='page_title',
            field=models.CharField(blank=True, default='', max_length=65),
        ),
        migrations.AddField(
            model_name='stock_image_category',
            name='page_description',
            field=models.CharField(blank=True, default='', max_length=165),
        ),
        migrations.AddField(
            model_name='stock_image_category',
            name='page_title',
            field=models.CharField(blank=True, default='', max_length=65),
        ),
    ]
