# Generated by Django 2.2.4 on 2020-06-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0109_auto_20200607_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='curated_category',
            name='second_description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='stock_image_category',
            name='second_description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
