# Generated by Django 2.2.4 on 2020-06-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0110_auto_20200614_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='curated_category',
            name='header',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='stock_image_category',
            name='header',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
