# Generated by Django 2.2.4 on 2020-07-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0111_auto_20200615_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_sms_email',
            name='customer_review_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_sms_email',
            name='customer_review_sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
