# Generated by Django 2.2.4 on 2020-07-20 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0112_auto_20200702_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='curated_category',
            name='parent_curated_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='artevenue.Curated_category'),
        ),
    ]
