# Generated by Django 2.2.4 on 2020-07-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0113_curated_category_parent_curated_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('PP', 'Payment Pending'), ('PC', 'In Process'), ('PR', 'In Production'), ('SH', 'Ready for Shipping'), ('IN', 'In Transit'), ('CO', 'Delivered'), ('CN', 'Cancelled')], default='PP', max_length=2),
        ),
        migrations.AlterField(
            model_name='order_shipping',
            name='pin_code',
            field=models.CharField(default='NA', max_length=10, null=True),
        ),
    ]
