# Generated by Django 2.2.4 on 2020-07-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0114_auto_20200730_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_shipping',
            old_name='pin_code',
            new_name='pin_code_id',
        ),
    ]
