# Generated by Django 2.2.4 on 2020-07-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0115_auto_20200730_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_billing',
            name='pin_code',
        ),
        migrations.AddField(
            model_name='order_billing',
            name='pin_code_id',
            field=models.CharField(default='NA', max_length=10, null=True),
        ),
    ]
