# Generated by Django 2.2.4 on 2020-07-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0116_auto_20200730_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_profile',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='channel_order_amz',
            name='billing_pin_code',
        ),
        migrations.RemoveField(
            model_name='channel_order_amz',
            name='shipping_pin_code',
        ),
        migrations.RemoveField(
            model_name='channel_partner',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='user_billing_address',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='user_shipping_address',
            name='pin_code',
        ),
        migrations.AddField(
            model_name='business_profile',
            name='pin_code_id',
            field=models.CharField(default='NA', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='channel_order_amz',
            name='billing_pin_code_id',
            field=models.CharField(default='NA', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='channel_order_amz',
            name='shipping_pin_code_id',
            field=models.CharField(default='NA', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='channel_partner',
            name='pin_code_id',
            field=models.CharField(default='NA', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user_billing_address',
            name='pin_code_id',
            field=models.CharField(default='NA', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user_shipping_address',
            name='pin_code_id',
            field=models.CharField(default='NA', max_length=10, null=True),
        ),
    ]
