# Generated by Django 2.2.4 on 2020-08-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0117_auto_20200730_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_profile',
            name='pin_code_id',
        ),
        migrations.RemoveField(
            model_name='channel_order_amz',
            name='billing_pin_code_id',
        ),
        migrations.RemoveField(
            model_name='channel_order_amz',
            name='shipping_pin_code_id',
        ),
        migrations.RemoveField(
            model_name='channel_partner',
            name='pin_code_id',
        ),
        migrations.RemoveField(
            model_name='order_billing',
            name='pin_code_id',
        ),
        migrations.RemoveField(
            model_name='order_shipping',
            name='pin_code_id',
        ),
        migrations.RemoveField(
            model_name='user_billing_address',
            name='pin_code_id',
        ),
        migrations.RemoveField(
            model_name='user_shipping_address',
            name='pin_code_id',
        ),
        migrations.AddField(
            model_name='business_profile',
            name='pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Pin_code'),
        ),
        migrations.AddField(
            model_name='channel_order_amz',
            name='billing_pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_pin_code', to='artevenue.Pin_code'),
        ),
        migrations.AddField(
            model_name='channel_order_amz',
            name='shipping_pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_pin_code', to='artevenue.Pin_code'),
        ),
        migrations.AddField(
            model_name='channel_partner',
            name='pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Pin_code'),
        ),
        migrations.AddField(
            model_name='order_billing',
            name='pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Pin_code'),
        ),
        migrations.AddField(
            model_name='order_shipping',
            name='pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Pin_code'),
        ),
        migrations.AddField(
            model_name='user_billing_address',
            name='pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Pin_code'),
        ),
        migrations.AddField(
            model_name='user_shipping_address',
            name='pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Pin_code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('PP', 'Payment Pending'), ('PC', 'In Process'), ('PR', 'In Production'), ('SH', 'Ready for Shipping'), ('IN', 'In Transit'), ('CO', 'Delivered')], default='PP', max_length=2),
        ),
    ]
