# Generated by Django 2.2.4 on 2020-08-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0118_auto_20200803_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_sms_email',
            name='shipping_sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('PP', 'Payment Pending'), ('PC', 'In Process'), ('PR', 'In Production'), ('SH', 'Ready for Shipping'), ('IN', 'In Transit'), ('CO', 'Delivered'), ('CN', 'Cancelled')], default='PP', max_length=2),
        ),
    ]
