# Generated by Django 2.2.4 on 2020-08-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0119_auto_20200817_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_sms_email',
            old_name='shipping_sms_sent',
            new_name='ready_to_ship_sms_sent',
        ),
        migrations.AddField(
            model_name='order_sms_email',
            name='tracking_info_sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
