# Generated by Django 2.2.4 on 2020-08-17 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0120_auto_20200817_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_sms_email',
            name='ready_to_ship_sms_sent',
        ),
        migrations.RemoveField(
            model_name='order_sms_email',
            name='tracking_info_sms_sent',
        ),
        migrations.CreateModel(
            name='Order_status_communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_production_sms_sent', models.BooleanField(default=False)),
                ('in_production_email_sent', models.BooleanField(default=False)),
                ('ready_to_ship_sms_sent', models.BooleanField(default=False)),
                ('ready_to_ship_email_sent', models.BooleanField(default=False)),
                ('tracking_info_sms_sent', models.BooleanField(default=False)),
                ('tracking_info_email_sent', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artevenue.Order')),
            ],
        ),
    ]
