# Generated by Django 2.2.4 on 2020-08-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0121_auto_20200817_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
