# Generated by Django 2.2.4 on 2020-09-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0122_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_art',
            name='image_type',
            field=models.CharField(choices=[('0', 'PAINTING'), ('1', 'PHOTOGRAPH')], max_length=1, null=True),
        ),
    ]
