# Generated by Django 2.2.4 on 2020-09-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0123_auto_20200908_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_art',
            name='art_surface',
            field=models.CharField(blank=True, choices=[('CVS', 'Canvas'), ('PPR', 'Paper')], default='', max_length=3),
        ),
    ]
