# Generated by Django 2.2.4 on 2020-10-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0125_auto_20200922_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount_flat',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount_flat',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount_slab',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount_slab',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
