# Generated by Django 2.2.4 on 2020-12-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0126_auto_20201003_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher_price',
            name='effective_from',
            field=models.DateField(default='2019-01-01'),
        ),
        migrations.AddField(
            model_name='publisher_price',
            name='effective_to',
            field=models.DateField(default='2099-01-01'),
        ),
        migrations.CreateModel(
            name='Framing_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(blank=True, default='', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('effective_from', models.DateField(default='2019-01-01')),
                ('effective_to', models.DateField(default='2099-01-01')),
                ('price_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.Price_type')),
            ],
        ),
    ]
