# Generated by Django 2.2.4 on 2020-12-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0127_auto_20201203_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='framing_price',
            old_name='component',
            new_name='component_type',
        ),
        migrations.AddField(
            model_name='framing_price',
            name='component_id',
            field=models.IntegerField(default=1),
        ),
    ]
