# Generated by Django 2.2.4 on 2021-01-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0128_auto_20201229_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('ONP', 'Online Payment'), ('COD', 'Cash on Delivery'), ('BKT', 'Bank Transfer'), ('CSH', 'Cash'), ('CDB', 'Cash Deposit in Bank Account')], default='ONP', max_length=3),
        ),
        migrations.AlterField(
            model_name='order_deferred_payment',
            name='mode_of_payment',
            field=models.CharField(choices=[('CS', 'Cash'), ('ON', 'Online'), ('CH', 'Cheque'), ('DD', 'Demand Draft'), ('BK', 'BANK TRANSFER - NEFT/IMPS/RTGS'), ('CD', 'Cash on Delivery')], max_length=2),
        ),
    ]
