# Generated by Django 2.2.4 on 2021-01-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0129_auto_20210108_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image_download',
            field=models.BooleanField(default=False, verbose_name='image download'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Business Support'), (2, 'Production'), (3, 'Sales'), (4, 'Marketting'), (5, 'Accounts'), (6, 'IT'), (0, 'Non-Employee Associate')], null=True),
        ),
    ]
