# Generated by Django 2.2.4 on 2021-03-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0130_auto_20210113_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generate_number_by_year',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('year', models.CharField(max_length=4)),
                ('current_number', models.IntegerField()),
            ],
        ),
    ]
