# Generated by Django 2.2.4 on 2021-05-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0132_stock_collage_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_collage_specs',
            name='mount_size',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
