# Generated by Django 2.2.4 on 2021-05-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0133_stock_collage_specs_mount_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_collage_specs',
            name='display_thumbnail_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='stock_collage_specs',
            name='display_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
