# Generated by Django 2.2.4 on 2021-05-23 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0134_auto_20210521_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_collage_specs',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock_collage_specs',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
