# Generated by Django 2.2.4 on 2021-05-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0135_auto_20210523_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_image',
            name='min_height',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
