# Generated by Django 2.2.4 on 2022-01-04 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('av_products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='av_product_varient_image',
            old_name='product_varient_id',
            new_name='product_varient',
        ),
    ]
