# Generated by Django 2.2.4 on 2022-01-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_products', '0002_auto_20220104_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='av_product_varient_article',
            name='stock_image_id',
            field=models.IntegerField(default=1),
        ),
    ]
