# Generated by Django 2.2.4 on 2022-01-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('av_products', '0003_av_product_varient_article_stock_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='av_product_varient_article',
            name='stock_image_id',
        ),
        migrations.AddField(
            model_name='av_product_varient_article',
            name='stock_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Stock_image'),
            preserve_default=False,
        ),
    ]
