# Generated by Django 2.2.4 on 2022-01-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_products', '0004_auto_20220105_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='av_product',
            name='artist',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='av_product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='av_product',
            name='image_type',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='av_product',
            name='max_height',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='av_product',
            name='max_width',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='av_product',
            name='min_height',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='av_product',
            name='min_width',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='av_product',
            name='orientation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='av_product',
            name='publisher',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='av_product_varient',
            name='thumbnail_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='av_product_varient',
            name='url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
