# Generated by Django 2.2.4 on 2020-03-15 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artevenue', '0092_auto_20200223_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_review_stock_image',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('featured', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=500)),
                ('rating', models.CharField(default='', max_length=1)),
                ('likes', models.CharField(default='', max_length=500)),
                ('review', models.CharField(default='', max_length=2000)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artevenue.Stock_image')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.Product_type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
