# Generated by Django 2.2.4 on 2020-03-15 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0092_auto_20200223_1017'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_review_stock_image',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.Country'),
        ),
        migrations.AddField(
            model_name='customer_review_stock_image',
            name='location',
            field=models.CharField(default='', max_length=500),
        ),
    ]
