# Generated by Django 2.2.4 on 2020-03-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20200315_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_review_stock_image',
            old_name='review',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='customer_review_stock_image',
            name='likes',
        ),
        migrations.AddField(
            model_name='customer_review_stock_image',
            name='email_id',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='customer_review_stock_image',
            name='headline',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer_review_stock_image',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
