# Generated by Django 2.2.4 on 2020-03-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20200316_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_review_stock_image',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.CreateModel(
            name='Customer_review_stock_image_pics',
            fields=[
                ('pic_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, default='', upload_to='user_photos/%Y/%m/%d/')),
                ('user_photo_thumbnail', models.ImageField(blank=True, default='', upload_to='user_photos/%Y/%m/%d/')),
                ('customer_review_stock_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Customer_review_stock_image')),
            ],
        ),
    ]
