# Generated by Django 2.2.4 on 2020-06-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20200322_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_review_stock_image',
            name='allow_to_use',
            field=models.BooleanField(default=True),
        ),
    ]
