# Generated by Django 2.2.4 on 2020-06-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_customer_review_stock_image_allow_to_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_review_stock_image_pics',
            name='disp_seq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
