CREATE OR REPLACE VIEW artist_art_view AS
SELECT "store_id" as store_id, "product_id" as product_id, "name" as name, "description" as description,
	"price" as price, "available_on" as available_on, "updated_at" as updated_at,
	"part_number" as part_number, 'STOCK-IMAGE' as product_type_id, "is_published" as is_published,  
	"seo_description" as seo_description, "seo_title" as seo_title, "charge_taxes" as charge_taxes, 
	"featured" as featured, "has_variants" as has_variants, "aspect_ratio" as aspect_ratio, 
	"image_type" as image_type, "orientation" as orientation, "max_width" as max_width,
	"max_height" as max_height, "min_width" as min_width, "publisher" as publisher, "artist" as artist,
	"colors" as colors, "key_words" as key_words, "url" as url, "thumbnail_url" as thumbnail_url,
	'' as session_id, 0 as user_id, '' as image_to_frame, '' as status, CURRENT_DATE as created_date, 
	CURRENT_DATE as updated_date, 0 as collage_layout_id, ''  as image_to_frame_thumbnail,
	0 as art_width , 0 as art_height, '' as art_medium, '' as art_surface, '' as art_surface_desc,
	'' as high_resolution_url, "category_disp_priority" as category_disp_priority,
	TRUE  art_print_allowed, 0 as original_art_price, 
	0 as available_qty, 0 as sold_qty, 0 as artist_id
FROM "artevenue_stock_image"
UNION
SELECT 0 as store_id, "artevenue_original_art"."product_id" as product_id, 
	"artevenue_original_art"."name" as name, 
	"artevenue_original_art"."description" as description,
	"artevenue_original_art"."price" as price, "artevenue_original_art"."available_on" as available_on, 
	CURRENT_DATE as updated_at,
	"artevenue_original_art"."part_number" as part_number, 
	'ORIGINAL-ART' as product_type_id, 
	"artevenue_original_art"."is_published" as is_published,  
	"artevenue_original_art"."seo_description" as seo_description, 
	"artevenue_original_art"."seo_title" as seo_title, 
	"artevenue_original_art"."charge_taxes" as charge_taxes, 
	"artevenue_original_art"."featured" as featured, "artevenue_original_art"."has_variants" as has_variants, 
	"artevenue_original_art"."aspect_ratio" as aspect_ratio, 
	"artevenue_original_art"."image_type" as image_type, 
	"artevenue_original_art"."orientation" as orientation, 
	"artevenue_original_art"."max_width" as max_width,
	"artevenue_original_art"."max_height" as max_height, 
	"artevenue_original_art"."min_width" as min_width, 
	"artevenue_original_art"."publisher" as publisher, 
	"artevenue_original_art"."artist" as artist,
	"artevenue_original_art"."colors" as colors, 
	"artevenue_original_art"."key_words" as key_words, 
	"artevenue_original_art"."url" as url, 
	"artevenue_original_art"."thumbnail_url" as thumbnail_url,
	'' as session_id, 0 as user_id, '' as image_to_frame, '' as status, CURRENT_DATE as created_date, 
	CURRENT_DATE as updated_date, 0 as collage_layout_id, ''  as image_to_frame_thumbnail,
	"artevenue_original_art"."art_width" as art_width , 
	"artevenue_original_art"."art_height" as art_height, 
	"artevenue_original_art"."art_medium" as art_medium, 
	"artevenue_original_art"."art_surface" as art_surface, 
	"artevenue_original_art"."art_surface_desc" as art_surface_desc,
	"artevenue_original_art"."high_resolution_url" as high_resolution_url, 
	"artevenue_original_art"."category_disp_priority" as category_disp_priority,
	"artevenue_original_art"."art_print_allowed" as  art_print_allowed, 
	"artevenue_original_art"."original_art_price" as original_art_price, 
	"artevenue_original_art"."available_qty" as available_qty, 
	"artevenue_original_art"."sold_qty" as sold_qty, 
	"artist_artist_original_art"."artist_id" as artist_id
FROM "artevenue_original_art", "artist_artist_original_art"
WHERE "artevenue_original_art"."product_id" = "artist_artist_original_art"."product_id"