# Generated by Django 2.2.4 on 2019-11-26 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artevenue', '0070_auto_20191121_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist_group',
            fields=[
                ('group_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('original_referral_fee_type', models.CharField(choices=[('PERCETNAGE', 'Percentage of Sale Price'), ('FLAT', 'Flat Fee')], max_length=10, null=True)),
                ('original_art_referral_fee', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('art_print_referral_fee_type', models.CharField(choices=[('PERCETNAGE', 'Percentage of Sale Price'), ('FLAT', 'Flat Fee')], max_length=10, null=True)),
                ('art_print_referral_fee', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=256)),
                ('last_name', models.CharField(default='', max_length=256)),
                ('artist_profile', models.CharField(default='', max_length=2000)),
                ('gallary_url', models.CharField(blank=True, default='', max_length=1000)),
                ('default_original_art_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('artist_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.Artist_group')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.Publisher')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artevenue.Ecom_site')),
            ],
        ),
    ]
