# Generated by Django 2.2.4 on 2019-11-26 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0073_auto_20191126_1812'),
        ('artist', '0002_delete_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=256)),
                ('last_name', models.CharField(default='', max_length=256)),
                ('artist_profile', models.CharField(default='', max_length=2000)),
                ('gallary_url', models.CharField(blank=True, default='', max_length=1000)),
                ('default_original_art_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('artist_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.Artist_group')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.Publisher')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artevenue.Ecom_site')),
            ],
        ),
        migrations.CreateModel(
            name='Artist_stock_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artevenue.Stock_image')),
            ],
        ),
        migrations.CreateModel(
            name='Artist_original_art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artevenue.Original_art')),
            ],
        ),
    ]
