# Generated by Django 2.2.4 on 2019-11-26 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0073_auto_20191126_1812'),
        ('artist', '0004_artist_art_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_udate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_qty', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artevenue.Original_art')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artevenue.Product_type')),
            ],
        ),
    ]
