# Generated by Django 2.2.4 on 2019-11-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_auto_20191127_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='artist',
            name='profile_photo',
            field=models.ImageField(blank=True, default='', upload_to='artist/profile_photo/uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='profile_tagline',
            field=models.CharField(default='', max_length=500),
        ),
    ]
