# Generated by Django 2.2.4 on 2019-11-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_auto_20191128_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_showcase1',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_showcase1_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_showcase2',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_showcase2_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_showcase3',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_showcase3_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='artist',
            name='url_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_photo',
            field=models.ImageField(blank=True, default='', upload_to='artist/profile_photo/%Y/%m/%d/'),
        ),
    ]
