# Generated by Django 2.2.4 on 2019-11-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0009_auto_20191130_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist_art_view',
        ),
    ]
