# Generated by Django 2.2.4 on 2019-11-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0010_delete_artist_art_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist_art_view',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available_on', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('part_number', models.CharField(max_length=30, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('seo_description', models.CharField(max_length=300, null=True)),
                ('seo_title', models.CharField(max_length=70, null=True)),
                ('charge_taxes', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('has_variants', models.BooleanField(default=False)),
                ('aspect_ratio', models.DecimalField(decimal_places=18, max_digits=21, null=True)),
                ('image_type', models.CharField(max_length=1, null=True)),
                ('orientation', models.CharField(max_length=20, null=True)),
                ('max_width', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('max_height', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('min_width', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('publisher', models.CharField(max_length=600, null=True)),
                ('colors', models.CharField(max_length=600, null=True)),
                ('key_words', models.CharField(max_length=2000, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=1000)),
                ('thumbnail_url', models.CharField(blank=True, default='', max_length=1000)),
                ('session_id', models.CharField(blank=True, default='', max_length=40)),
                ('image_to_frame', models.ImageField(blank=True, default='', upload_to='uploads/%Y/%m/%d/')),
                ('image_to_frame_thumbnail', models.ImageField(blank=True, default='', upload_to='uploads/%Y/%m/%d/')),
                ('status', models.CharField(blank=True, max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('collage_layout_id', models.IntegerField(null=True)),
                ('high_resolution_url', models.CharField(blank=True, default='', max_length=1000)),
                ('art_width', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('art_height', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('art_medium', models.CharField(blank=True, default='', max_length=3)),
                ('art_surface', models.CharField(blank=True, default='', max_length=3)),
                ('art_surface_desc', models.CharField(blank=True, default='', max_length=500)),
                ('category_disp_priority', models.IntegerField(null=True)),
                ('art_print_allowed', models.BooleanField(default=False)),
                ('original_art_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('available_qty', models.IntegerField()),
                ('sold_qty', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'artist_art_view',
                'managed': False,
            },
        ),
    ]
