# Generated by Django 2.2.4 on 2020-08-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0011_artist_art_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
