# Generated by Django 2.2.4 on 2020-09-08 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0012_auto_20200829_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='generate_art_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('PART', 'Part Number'), ('ORIG', 'Original ID'), ('STKI', 'Stock Image ID')], max_length=4)),
                ('prefix', models.CharField(max_length=10)),
                ('suffix', models.CharField(default='', max_length=10)),
                ('current_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='artist_original_art',
            name='approval_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='artist_original_art',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artist_original_art',
            name='artist_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artist_original_art',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist_original_art',
            name='sell_mode',
            field=models.CharField(choices=[('O', 'ONLY ORIGINAL'), ('A', 'ONLY ART PRINT'), ('B', 'BOTH')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='artist_original_art',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='artist_stock_image',
            name='approval_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='artist_stock_image',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artist_stock_image',
            name='artist_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artist_stock_image',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist_stock_image',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
