# Generated by Django 2.2.4 on 2020-09-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0013_auto_20200908_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='generate_art_number',
        ),
    ]
