# Generated by Django 2.2.4 on 2020-09-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0016_auto_20200910_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist_original_art',
            name='uploaded_date',
            field=models.DateField(null=True),
        ),
    ]
