# Generated by Django 2.2.4 on 2020-09-18 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0123_auto_20200908_1054'),
        ('artist', '0017_artist_original_art_uploaded_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist_sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
                ('part_number', models.CharField(max_length=30, null=True)),
                ('order_item_id', models.IntegerField(default=0)),
                ('sale_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('license_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pay_date', models.DateField(null=True)),
                ('pay_reference', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artevenue.Order')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artevenue.Product_type')),
            ],
        ),
    ]
