# Generated by Django 2.2.4 on 2020-09-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0018_artist_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist_original_art',
            name='unapproval_reason',
            field=models.CharField(default='', max_length=500),
        ),
    ]
