# Generated by Django 2.2.4 on 2020-09-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0019_artist_original_art_unapproval_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist_art_view',
        ),
        migrations.AddField(
            model_name='artist_original_art',
            name='artist_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
