# Generated by Django 2.2.4 on 2020-10-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0020_auto_20200920_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist_original_art',
            name='unapproval_reason',
            field=models.CharField(choices=[('I', 'Artwork image is not fit for listing, Please upload another image. Follow image guidelines.'), ('X', 'Artwork not found fit for listing'), ('O', 'Other reason (Please get in touch with us)')], default='', max_length=1),
        ),
    ]
