# Generated by Django 2.2.4 on 2020-09-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallerywalls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='room_view_thumbnail_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
