# Generated by Django 2.2.4 on 2020-09-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallerywalls', '0002_gallery_room_view_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12500, max_digits=12),
            preserve_default=False,
        ),
    ]
