# Generated by Django 2.2.4 on 2020-09-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallerywalls', '0003_gallery_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery_item',
            name='acrylic',
        ),
        migrations.RemoveField(
            model_name='gallery_item',
            name='board',
        ),
        migrations.RemoveField(
            model_name='gallery_item',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='gallery_item',
            name='moulding',
        ),
        migrations.RemoveField(
            model_name='gallery_item',
            name='mount',
        ),
        migrations.RemoveField(
            model_name='gallery_item',
            name='print_medium',
        ),
        migrations.RemoveField(
            model_name='gallery_item',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='gallery_item',
            name='stretch',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='room',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Gallery_item',
        ),
    ]
