# Generated by Django 2.2.4 on 2020-09-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallerywalls', '0005_gallery_gallery_item_gallery_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='num_of_images',
        ),
    ]
